name: Build and Package (Windows)

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '7.0.x'

      - name: Restore and Publish
        run: |
          dotnet restore src\LawOfficeApp.csproj
          dotnet publish src\LawOfficeApp.csproj -c Release -r win-x64 /p:PublishSingleFile=true /p:PublishTrimmed=false /p:PublishReadyToRun=true -o publish

      - name: Install Inno Setup (choco)
        run: |
          choco install innosetup -y
          refreshenv

      - name: Build installer with Inno Setup
        run: |
          '"C:\Program Files (x86)\Inno Setup 6\ISCC.exe"' installer_scripts\lawoffice_installer.iss

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: lawoffice-installers
          path: |
            publish/**
            *.exe
            *.msi
