name: Build Publish (single-file)

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-2022

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '7.0.x'

      - name: Restore
        run: dotnet restore src/LawOfficeApp.csproj

      - name: Publish self-contained single-file
        run: dotnet publish src/LawOfficeApp.csproj -c Release -r win-x64 --self-contained true /p:PublishSingleFile=true -o publish

      - name: Show publish files
        run: dir publish
        shell: powershell

      - name: Zip publish folder
        run: Compress-Archive -Path publish\* -DestinationPath lawoffice_publish.zip
        shell: powershell

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: lawoffice_publish
          path: lawoffice_publish.zip
