name: Build Windows Setup

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-2022

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup .NET (7.x)
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '7.0.x'

      - name: Restore dependencies
        run: dotnet restore src/LawOfficeApp.csproj

      - name: Publish (self-contained single-file)
        run: dotnet publish src/LawOfficeApp.csproj -c Release -r win-x64 --self-contained true /p:PublishSingleFile=true -o publish

      - name: Show publish files (for debug)
        run: dir publish
        shell: powershell

      - name: Install Inno Setup
        run: choco install innosetup --no-progress -y

      - name: Build installer with Inno Setup
        run: '"C:\Program Files (x86)\Inno Setup 6\ISCC.exe" installer_scripts\lawoffice_installer.iss'

      - name: List repository root (for debug)
        run: dir
        shell: powershell

      - name: Upload installer artifact
        uses: actions/upload-artifact@v4
        with:
          name: LawOfficeInstaller
          path: |
            **\*.exe
            publish\**
