name: Build Windows Setup

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v3

      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '8.0.x'

      - name: Restore dependencies
        run: dotnet restore

      - name: Build Release
        run: dotnet publish -c Release -r win-x64 --self-contained true /p:PublishSingleFile=true

      - name: Install Inno Setup
        run: choco install innosetup --yes

      - name: Create Inno Setup script
        run: |
          echo [Setup] > installer.iss
          echo AppName=Law Office Manager >> installer.iss
          echo AppVersion=1.0 >> installer.iss
          echo DefaultDirName={pf}\LawOfficeManager >> installer.iss
          echo DefaultGroupName=LawOfficeManager >> installer.iss
          echo OutputBaseFilename=LawOfficeManagerSetup >> installer.iss
          echo [Files] >> installer.iss
          echo Source: "bin\Release\net8.0-windows\win-x64\publish\*"; DestDir: "{app}"; Flags: recursesubdirs >> installer.iss
          echo [Icons] >> installer.iss
          echo Name: "{group}\Law Office Manager"; Filename: "{app}\LawOfficeManager.exe" >> installer.iss
          echo Name: "{commondesktop}\Law Office Manager"; Filename: "{app}\LawOfficeManager.exe" >> installer.iss

      - name: Build installer
        run: iscc installer.iss

      - name: Upload installer
        uses: actions/upload-artifact@v4
        with:
          name: LawOfficeManagerSetup
          path: LawOfficeManagerSetup.exe
